apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
  namespace: cora-ai-chatbot
spec:
  replicas: 1
  selector:
    io.kompose.service: server
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/chroma-openshift-net: "true"
        io.kompose.service: server
    spec:
      containers:
        - image: ' '
          name: server
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /chroma/.chroma/index
              name: index-data
      restartPolicy: Always
      volumes:
        - name: index-data
          persistentVolumeClaim:
            claimName: index-data
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - server
        from:
          kind: ImageStreamTag
          name: server:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
